### ISSUE TITLE
OS X install instructions incomplete

### ISSUE THREAD

**Issue by lacker** [facebook/iTorch#21]
I followed the OS X install instructions but was missing some dependencies and had to add on:

pip install pyzmq
pip install jinja2
pip install tornado

Was I doing something wrong or is this unsurprising? If this is just a missing instructions issue then I can submit a pull request to change the setup docs if you like.

**Comment by soumith** [comment]
if you install ipython via anaconda, i believe they come prepackaged. that's why I did not notice them.  
I differed ipython install instructions to the ipython page, I did not explicitly specify the dependencies for ipython, or how to install it. I feel like if I specify them here, they'll only go out of date very soon.

**Comment by lacker** [comment]
I see. OK fair enough
